CREATE TABLE College(
	col_id number(4) CONSTRAINT col_pk PRIMARY KEY DEFERRABLE INITIALLY IMMEDIATE,
	title varchar(100) CONSTRAINT col_title_nn NOT NULL DEFERRABLE INITIALLY IMMEDIATE,
	dean varchar(21)
);