CREATE TABLE Course(
	cou_id number CONSTRAINT cou_pk PRIMARY KEY DEFERRABLE INITIALLY IMMEDIATE,
	name varchar(100) CONSTRAINT cou_name_nn NOT NULL DEFERRABLE INITIALLY IMMEDIATE,
	cou_desc varchar(1000) CONSTRAINT cou_desc_nn NOT NULL DEFERRABLE INITIALLY IMMEDIATE,
	dept_id number(3),
	CONSTRAINT cou_dept_fk FOREIGN KEY(dept_id) REFERENCES Department(dept_id) DEFERRABLE INITIALLY IMMEDIATE
);