CREATE TABLE Student(
	stu_id number(7) CONSTRAINT stu_pk PRIMARY KEY DEFERRABLE INITIALLY IMMEDIATE,
	email varchar(15) CONSTRAINT stu_email_nn NOT NULL DEFERRABLE INITIALLY IMMEDIATE,
	grade_level number(3) CONSTRAINT stu_gl_nn NOT NULL DEFERRABLE INITIALLY IMMEDIATE,
	first_name varchar(10) CONSTRAINT stu_fn_nn NOT NULL DEFERRABLE INITIALLY IMMEDIATE,
	last_name varchar(10) CONSTRAINT stu_ln_nn NOT NULL DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE Instructor(
	int_id number(7) CONSTRAINT int_pk PRIMARY KEY DEFERRABLE INITIALLY IMMEDIATE,
	email varchar(50) CONSTRAINT int_email_nn NOT NULL DEFERRABLE INITIALLY IMMEDIATE,
	first_name varchar(10) CONSTRAINT int_fn_nn NOT NULL DEFERRABLE INITIALLY IMMEDIATE,
	last_name varchar(10) CONSTRAINT int_ln_nn NOT NULL DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE College(
	col_id number(4) CONSTRAINT col_pk PRIMARY KEY DEFERRABLE INITIALLY IMMEDIATE,
	title varchar(100) CONSTRAINT col_title_nn NOT NULL DEFERRABLE INITIALLY IMMEDIATE,
	dean varchar(21)
);

CREATE TABLE Department(
	dept_id number(3) CONSTRAINT dept_pk PRIMARY KEY DEFERRABLE INITIALLY IMMEDIATE,
	chair varchar(21),
	title varchar(100) CONSTRAINT dept_title_nn NOT NULL DEFERRABLE INITIALLY IMMEDIATE,
	col_id number(4),
	CONSTRAINT dept_col_fk FOREIGN KEY(col_id) REFERENCES College(col_id) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE Course(
	cou_id number CONSTRAINT cou_pk PRIMARY KEY DEFERRABLE INITIALLY IMMEDIATE,
	name varchar(100) CONSTRAINT cou_name_nn NOT NULL DEFERRABLE INITIALLY IMMEDIATE,
	cou_desc varchar(1000) CONSTRAINT cou_desc_nn NOT NULL DEFERRABLE INITIALLY IMMEDIATE,
	dept_id number(3),
	CONSTRAINT cou_dept_fk FOREIGN KEY(dept_id) REFERENCES Department(dept_id) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE CourseSection(
	cs_id number(4) CONSTRAINT cs_pk PRIMARY KEY DEFERRABLE INITIALLY IMMEDIATE,
	cs_date date CONSTRAINT cs_date_nn NOT NULL DEFERRABLE INITIALLY IMMEDIATE,
	int_id number(7),
	cou_id number(4),
	CONSTRAINT cs_cou_fk FOREIGN KEY(cou_id) REFERENCES Course(cou_id) DEFERRABLE INITIALLY IMMEDIATE,
	CONSTRAINT cs_int_fk FOREIGN KEY(int_id) REFERENCES Instructor(int_id) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE ClassSchedule(
	cs_id number(4),
	stu_id number(7),
	CONSTRAINT cl_stu_fk FOREIGN KEY(stu_id) REFERENCES Student(stu_id) DEFERRABLE INITIALLY IMMEDIATE,
	CONSTRAINT cl_cs_fk FOREIGN KEY(cs_id) REFERENCES CourseSection(cs_id) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE Accusation(
	acc_id number(4) CONSTRAINT acc_pk PRIMARY KEY DEFERRABLE INITIALLY IMMEDIATE,
	acc_date date CONSTRAINT acc_date_nn NOT NULL DEFERRABLE INITIALLY IMMEDIATE,
	type varchar(10) CONSTRAINT acc_type_nn NOT NULL DEFERRABLE INITIALLY IMMEDIATE,
	evidence varchar(1000) CONSTRAINT acc_evid_nn NOT NULL DEFERRABLE INITIALLY IMMEDIATE,
	status varchar(25),
	cs_id number(4),
	stu_id number(7),
	int_id number(7),
	CONSTRAINT acc_cs_fk FOREIGN KEY(cs_id) REFERENCES CourseSection(cs_id) DEFERRABLE INITIALLY IMMEDIATE,
	CONSTRAINT acc_int_fk FOREIGN KEY(int_id) REFERENCES Instructor(int_id) DEFERRABLE INITIALLY IMMEDIATE,
	CONSTRAINT acc_stu_fk FOREIGN KEY(stu_id) REFERENCES Student(stu_id) DEFERRABLE INITIALLY IMMEDIATE
);