CREATE TABLE Student(
	stu_id number(7) CONSTRAINT stu_pk PRIMARY KEY DEFERRABLE INITIALLY IMMEDIATE,
	email varchar(15) CONSTRAINT stu_email_nn NOT NULL DEFERRABLE INITIALLY IMMEDIATE,
	grade_level number(3) CONSTRAINT stu_gl_nn NOT NULL DEFERRABLE INITIALLY IMMEDIATE,
	first_name varchar(10) CONSTRAINT stu_fn_nn NOT NULL DEFERRABLE INITIALLY IMMEDIATE,
	last_name varchar(10) CONSTRAINT stu_ln_nn NOT NULL DEFERRABLE INITIALLY IMMEDIATE
);